### PR TITLE
Extract library definitions

### PR DESCRIPTION
**Pull request by zsoltk**

### CODE REVIEW

**Comment by vanniktech** [comment]
Hmm maybe dependencies.gradle

**Comment by zsoltk** [comment]
Done

**Comment by vanniktech** [comment]
:+1:

**Comment by artem-zinnatullin** [comment]
@zsoltk please also change comment here https://github.com/artem-zinnatullin/qualitymatters/blob/master/app/build.gradle#L113

:+1:

**Comment by zsoltk** [comment]
Done.

**Comment by artem-zinnatullin** [comment]
:+1:

**Pull request merged**
