### PR TITLE
Update Dagger to 2.3

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
No changelog though, here is [diff between 2.2 and 2.3](https://github.com/google/dagger/compare/dagger-2.2...dagger-2.3).

### CODE REVIEW

**Comment by vanniktech** [comment]
:+1: @artem-zinnatullin have you used the new `@Resuable` yet and got any experience / gotchas with it?

**Comment by jbaginski** [comment]
https://github.com/google/dagger/issues/356

**Comment by artem-zinnatullin** [comment]
Ah, yeah they have problems with different Guava versions across dependencies. Let's wait for resolution then, not sure I want to specify guava explicitly for `apt`. Thanks @jbaginski 

@vanniktech haven't use `@Reusable` yet

**Comment by lenguyenthanh** [comment]
`@Reusable` looks cool: http://google.github.io/dagger/users-guide.html#reusable-scope but I don't think @artem-zinnatullin will like it 😄

**Comment by lenguyenthanh** [comment]
Btw, after Dagger 2.2 do we need these dependencies any more:
````
    compile libraries.javaxInject
    compile libraries.javaxAnnotationApi
````

**Comment by artem-zinnatullin** [comment]
Closing in favor of #166.

**Pull request closed without merging**
