### PR TITLE
hacktober fest

### PR DESCRIPTION
**Pull request by liaminatorshearin49**
please accept im trying to get my hacktober fest tshirt

### CODE REVIEW

**Comment by caipivara** [comment]
@liaminatorshearin49 But what this PR is trying to do?

**Comment by vgaidarji** [comment]
Looks like hacktoberfest t-shirt vampirism

**Comment by vanniktech** [comment]
That's avoidable though. Just gotta go and add the invalid label to this PR

**Comment by artem-zinnatullin** [comment]
Wow, that is a pretty confusing PR, as far as I see it doesn't actually do anything because it reuses old commits made by other contributors (most likely rebased with new author).

That is definitely not something we want to happen in this project, sorry @liaminatorshearin49. 

You can actually update some libraries, make code better, etc in separate PRs with reasonable description of why change is required to get your t-shirt :)

I'm closing this one, sorry.

**Pull request closed without merging**
