### PR TITLE
Feature/add gradle scan plugin

### PR DESCRIPTION
**Pull request by caipivara**

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
@danielgomezrico trying to find out reason of OOM?

**Comment by danielgomezrico** [comment]
@artem-zinnatullin yeah but tests run, where do you see the OOM?

**Comment by artem-zinnatullin** [comment]
If it would be deterministic, it wouldn't be such a pain in the ass…

**Comment by danielgomezrico** [comment]
@artem-zinnatullin can you build it until it fails? Im trying closing and reopening the PR but it always pass

**Comment by artem-zinnatullin** [comment]
sure

**Comment by danielgomezrico** [comment]
@artem-zinnatullin I already saw the failing ones, sorry for that, what Im thinking:

Im seeing this https://circleci.com/gh/artem-zinnatullin/qualitymatters/153 and https://circleci.com/gh/artem-zinnatullin/qualitymatters/174 and looks like the same issue but before gradle scan code was in the repo, maybe OOM is not related to gradle scan?

**Comment by caipivara** [comment]
This feature is already on build.sh

**Pull request closed without merging**
