### PR TITLE
Remove StethoInterceptor from DeveloperSettingsModel

### PR DESCRIPTION
**Pull request by se-bastiaan**
From what I can see the StethoInterceptor was moved to the OkHttpInterceptorsModule. And this doesn't work anymore.

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Oh shi, thanks! Pls fix import (see Travis). 

Would be great to cover Developer Settings with functional test..

**Comment by se-bastiaan** [comment]
I'll squash the commits tomorrow. :zzz: now

**Comment by artem-zinnatullin** [comment]
ping @se-bastiaan :)

@vanniktech PTAL

**Comment by vanniktech** [comment]
:+1:

**Comment by se-bastiaan** [comment]
@artem-zinnatullin Done. Also removed the okhttp from the developersettingsmodelimpl and the test now.

**Comment by artem-zinnatullin** [comment]
:+1:, @se-bastiaan!

**Pull request merged**
