### PR TITLE
Update RxJava to version 1.1.3

### PR DESCRIPTION
**Pull request by lenguyenthanh**
Changelog here: https://github.com/ReactiveX/RxJava/releases/tag/v1.1.3

### CODE REVIEW

**Comment by vanniktech** [comment]
:+1:

**Comment by artem-zinnatullin** [comment]
:+1: (will merge after CI)

**Comment by lenguyenthanh** [comment]
With two Cis we have double chances to fail 😄

**Comment by artem-zinnatullin** [comment]
Well, yeah, flucking Android Emulator :(

**Pull request merged**
