### PR TITLE
Update Auto Value to 1.2

### PR DESCRIPTION
**Pull request by vanniktech**
1.3 also coming soon (at least I hope)

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Pls rebase

**Comment by vanniktech** [comment]
@artem-zinnatullin  done

**Comment by vanniktech** [comment]
CircleCI is flaky :(

**Comment by vanniktech** [comment]
@artem-zinnatullin this is now green on both CIs

**Comment by artem-zinnatullin** [comment]
:+1:

**Pull request merged**
