### PR TITLE
Update ButterKnife to 8.2.1

### PR DESCRIPTION
**Pull request by vanniktech**

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Looks like findbugs is not happy about butterknife update!

**Comment by vanniktech** [comment]
Yeah true will look into it.

**Comment by vanniktech** [comment]
Should I ignore the findbugs warnings or simply add null checks?

**Comment by artem-zinnatullin** [comment]
Yes, let's try :)

**Comment by artem-zinnatullin** [comment]
👍

**Pull request merged**
