### PR TITLE
master: DeveloperSettingsFragment slightly refactored.

### PR DESCRIPTION
**Pull request by rcd27**
Moved a generic-type methods to BaseFragment for setting text to TextVews and setting state to Switches.

### CODE REVIEW

**Review by vanniktech — APPROVED** [review]
It's slightly better but donno whether it's worth it. CI is failing though.

**Comment by rcd27** [comment]
Oh, how can I check out the CI?

**Comment by emartynov** [comment]
Same thoughts! Is it good to have in the base fragment or utility class? 

I'm also not the fan of the `assert` in production code (My preference runtime exceptions with clear messages) but this is a completely separate topic not related to PR.

**Comment by rcd27** [comment]
Well, we can leave this logic in this DeveloperSettingsFragment so it would be more clear. But I still think generics make this code a bit better.

**Pull request closed without merging**
