### PR TITLE
Add RxLint

### PR DESCRIPTION
**Pull request by vanniktech**
http://www.littlerobots.nl/blog/RxLint-a-lint-rule-for-RxJava/

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Was on my list :) :+1: 

Strange to see 0 warnings, in NY Times I got ~15 false-positives (already reported)

**Comment by lenguyenthanh** [comment]
👍 great tool, will add to my project as well.

**Comment by Rainer-Lang** [comment]
Me too

**Comment by vanniktech** [comment]
@artem-zinnatullin anything against merging it?

**Comment by artem-zinnatullin** [comment]
@vanniktech only my lack of time this week (and at least few next weeks too…)

sorry

**Pull request merged**
