### PR TITLE
Remove @NonNull in QualityMattersApp

### PR DESCRIPTION
**Pull request by vanniktech**
As discussed in #89 

@artem-zinnatullin should I also remove this 'code style' in other classes? (e.g. tests)

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
>should I also remove this 'code style' in other classes? (e.g. tests)

yup, let's do it. After writing more and more Kotlin code I can't normally read this too…

**Comment by Plastix** [comment]
I'm just curious what the rationale is. I saw you advocating for the support annotations on a different thread @artem-zinnatullin.

**Comment by artem-zinnatullin** [comment]
Well, you "never" inject null dependencies, the only valid case is for properties that you can't instantiate in constructor but, with suppressing warning it takes 2 lines.. 

I haven't reviewed the PR yet, hope @vanniktech won't delete annotations everywhere :D

**Comment by Plastix** [comment]
Thanks for the explanation @artem-zinnatullin. I agree with that rationale.

**Comment by artem-zinnatullin** [comment]
Np :) I was a fan of it for long time but I agree that it's too verbose.

**Comment by lenguyenthanh** [comment]
I'm sure @vanniktech delete them only in application class 😄 Java is to verbose, that one reason why people are excited about Kotlin.

**Comment by vanniktech** [comment]
@lenguyenthanh & @artem-zinnatullin don't worry guys I just removed it where I thought I had to

**Comment by artem-zinnatullin** [comment]
:+1: (please fix imports, build failed)

**Comment by vanniktech** [comment]
Ups removed one too many :D @artem-zinnatullin do I need to squash manually or are we using here already the new feature of Github?

**Comment by artem-zinnatullin** [comment]
Squashed on GitHub, thanks!

// sorry for delays, as said before I have veery small amounts of "that" time at the moment…

**Pull request merged**
