### PR TITLE
Save memory on CI

### PR DESCRIPTION
**Pull request by IgorGanapolsky**
Save memory on CI

(cherry picked from commit 9322fd1fc93c2750354b30bf94f021ae92dd8919)

Update gradle version, build tools version.

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Oh lol :D 

I've never experienced situation when somebody picked my unfinished branch and made a PR from it. Can't say that I'm angry or something because you've finished what I wanted to do anyway, but it was a surprise, please ping me first before doing that in future!

**Comment by artem-zinnatullin** [comment]
Please also add `build-tools-23.0.3` to `.travis.yml` and `circle.yml`

**Comment by IgorGanapolsky** [comment]
Sorry about that.  I had no idea how the cherry pick got involved in this
PR.  I guess it was my git mistake.

On Thu, Jun 16, 2016 at 9:57 AM, Artem Zinnatullin <notifications@github.com

**Comment by IgorGanapolsky** [comment]
Updated travis and circle ci.

**Comment by artem-zinnatullin** [comment]
FindBugs failed, please run `bash ci.sh` before updating PR to check that everything passes locally

**Comment by IgorGanapolsky** [comment]
I don't understand what these findbugs errors mean:
screen shot 2016-06-16 at 4 56 08 pm

I did not touch this code, so why is it breaking?

**Comment by artem-zinnatullin** [comment]
Because you've used my `ci` script which now strictly orders execution and runs tests **before** checks like FindBugs.

Looks like in past FindBug run **before** tests and didn't analyze test sources, now it does, so yeah

**Comment by IgorGanapolsky** [comment]
Since I have no idea how to deal with this FindBugs madness, I am closing this PR.

**Pull request closed without merging**
