### PR TITLE
Update AndroidDevMetrics version 0.4

### PR DESCRIPTION
**Pull request by lenguyenthanh**
Changelog here: https://github.com/frogermcs/AndroidDevMetrics/blob/master/CHANGELOG.md
New Blog here: http://frogermcs.github.io/androiddevmetrics-activity-lifecycle-methods-tracing/
Thanks @frogermcs for a great library.
p/s: We still need no-op version for testing.

### CODE REVIEW

**Comment by vanniktech** [comment]
:+1:

**Comment by artem-zinnatullin** [comment]
Nice! I'll check how it works today and merge if everything is ok.

**Comment by artem-zinnatullin** [comment]
Thanks, @lenguyenthanh!

**Comment by lenguyenthanh** [comment]
Please don't thanks me every time, @artem-zinnatullin. I've learnt a lot from this and it's a time to give back.

**Comment by artem-zinnatullin** [comment]
But what if I really want to say "thank you" ? This is how I speak in real life! 

And I really appreciate your contributions to the project, so, please be strong and accept my thanks :) 

@vanniktech gone through that in this project and I've asked him to review PRs too and only some amount of time later I stopped writing "thanks" to him because it's now established relationship and I still mean "thanks" for his contributions under the hood. 

So, the only way to stop me is to agree reviewing PRs to this project (yes this is invitation) :)

**Comment by lenguyenthanh** [comment]
@artem-zinnatullin I definitely want to stop you ;) Thank you for inviting me to review PRs. I really appreciate this. Reviewing is interesting way to learn. I'll try my best to do this work.

**Comment by artem-zinnatullin** [comment]
Great, I'm fan of 2 :+1: before merge, now it'll be possible no matter who is author of the PR!

**Comment by lenguyenthanh** [comment]
So we'll have 2 :+1: rule for any PR from now ;)

**Pull request merged**
