### PR TITLE
Make findbugs XML report human readable

### PR DESCRIPTION
**Pull request by karlicoss**
Make Findbugs great again!

Before:
```
BugInstance type="ST_WRITE_TO_STATIC_FROM_INSTANCE_METHOD" priority="1" rank="15" abbrev="ST" category="STYLE">
<Class classname="com.artemzin.qualitymatters.ApplicationModule">
<SourceLine classname="com.artemzin.qualitymatters.ApplicationModule" start="28" end="52" sourcefile="ApplicationModule.java" sourcepath="com/artemzin/qualitymatters/ApplicationModule.java"/>
</Class>
<Method classname="com.artemzin.qualitymatters.ApplicationModule" name="providePicasso" signature="(Lcom/artemzin/qualitymatters/QualityMattersApp;Lcom/squareup/okhttp/OkHttpClient;)Lcom/squareup/picasso/Picasso;" isStatic="false">
<SourceLine classname="com.artemzin.qualitymatters.ApplicationModule" start="49" end="52" startBytecode="0" endBytecode="100" sourcefile="ApplicationModule.java" sourcepath="com/artemzin/qualitymatters/ApplicationModule.java"/>
</Method>
<Field classname="com.artemzin.qualitymatters.ApplicationModule" name="res" signature="Z" isStatic="true">
<SourceLine classname="com.artemzin.qualitymatters.ApplicationModule" sourcefile="ApplicationModule.java" sourcepath="com/artemzin/qualitymatters/ApplicationModule.java"/>
</Field>
<SourceLine classname="com.artemzin.qualitymatters.ApplicationModule" start="49" end="49" startBytecode="1" endBytecode="1" sourcefile="ApplicationModule.java" sourcepath="com/artemzin/qualitymatters/ApplicationModule.java"/>
</BugInstance>
```

After:

```
<BugInstance type="ST_WRITE_TO_STATIC_FROM_INSTANCE_METHOD" priority="1" rank="15" abbrev="ST" category="STYLE" instanceHash="ec8dbc7f7d490ee70fda50b4793f615f" instanceOccurrenceNum="0" instanceOccurrenceMax="0">
<ShortMessage>Write to static field from instance method</ShortMessage>
<LongMessage>
Write to static field com.artemzin.qualitymatters.ApplicationModule.res from instance method com.artemzin.qualitymatters.ApplicationModule.providePicasso(QualityMattersApp, OkHttpClient)
</LongMessage>
<Class classname="com.artemzin.qualitymatters.ApplicationModule" primary="true">
<SourceLine classname="com.artemzin.qualitymatters.ApplicationModule" start="28" end="52" sourcefile="ApplicationModule.java" sourcepath="com/artemzin/qualitymatters/ApplicationModule.java">
<Message>At ApplicationModule.java:[lines 28-52]</Message>
</SourceLine>
<Message>
In class com.artemzin.qualitymatters.ApplicationModule
</Message>
</Class>
<Method classname="com.artemzin.qualitymatters.ApplicationModule" name="providePicasso" signature="(Lcom/artemzin/qualitymatters/QualityMattersApp;Lcom/squareup/okhttp/OkHttpClient;)Lcom/squareup/picasso/Picasso;" isStatic="false" primary="true">
<SourceLine classname="com.artemzin.qualitymatters.ApplicationModule" start="49" end="52" startBytecode="0" endBytecode="100" sourcefile="ApplicationModule.java" sourcepath="com/artemzin/qualitymatters/ApplicationModule.java"/>
<Message>
In method com.artemzin.qualitymatters.ApplicationModule.providePicasso(QualityMattersApp, OkHttpClient)
</Message>
</Method>
<Field classname="com.artemzin.qualitymatters.ApplicationModule" name="res" signature="Z" isStatic="true" primary="true">
<SourceLine classname="com.artemzin.qualitymatters.ApplicationModule" sourcefile="ApplicationModule.java" sourcepath="com/artemzin/qualitymatters/ApplicationModule.java">
<Message>In ApplicationModule.java</Message>
</SourceLine>
<Message>
Field com.artemzin.qualitymatters.ApplicationModule.res
</Message>
</Field>
<SourceLine classname="com.artemzin.qualitymatters.ApplicationModule" primary="true" start="49" end="49" startBytecode="1" endBytecode="1" sourcefile="ApplicationModule.java" sourcepath="com/artemzin/qualitymatters/ApplicationModule.java">
<Message>At ApplicationModule.java:[line 49]</Message>
</SourceLine>
</BugInstance>
```

This makes XML reports rendered by CIs (e.g. Teamcity) human readable.

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Nice! :+1:

**Comment by vanniktech** [comment]
Hmm fair enough change though, I'd rater go with something like this

```groovy
reports {
    xml {
        enabled = isCI
    }
    html {
        enabled = !isCI
    }
}
```

So we get HTML reports locally and for the CI XML since most of the plugins use the XML for displaying the failures.

**Comment by artem-zinnatullin** [comment]
@vanniktech I'd prefer to have same output on CI and locally, it's a huge fail that Gradle finbugs plugin doesn't support both options simultaneously…

**Comment by vanniktech** [comment]
I think some plugins do support that. But I can't remember which ones. Also Checkstyle HTML support was just added with Gradle 2.10 ....

**Comment by artem-zinnatullin** [comment]
@vanniktech let's merge this as is and then add both `html` and `xml` once Gradle will add support for it?

**Comment by vanniktech** [comment]
Sounds good :+1:

**Pull request merged**
