### PR TITLE
Update Dagger to 2.2

### LINKED ISSUE #78: Dagger Note
While running the project locally I got that note.

> Note: Generating a MembersInjector or Factory for com.artemzin.qualitymatters.QualityMattersApp. Prefer to run the dagger processor over that class instead.

Should we pay attention to this one?

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
Probably it'll fix #78 idk 

Changelog https://github.com/google/dagger/blob/master/CHANGELOG.md#version-22-2016-03-22

### CODE REVIEW

**Comment by lenguyenthanh** [comment]
:+1: But #78 is still happen.

**Comment by vanniktech** [comment]
:+1:

**Comment by vanniktech** [comment]
@artem-zinnatullin the issue #78 was accidentally closed since you wrote `fix #78` and the probably it'll was not read :D

**Comment by artem-zinnatullin** [comment]
oh shi, my bad, reopened :D

**Pull request merged**
