### PR TITLE
Update Dagger to 2.4

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
No changelog as always https://github.com/google/dagger/blob/master/CHANGELOG.md#change-log

### CODE REVIEW

**Comment by lenguyenthanh** [comment]
At least it fix dependency problem. 👍

**Comment by Plastix** [comment]
@artem-zinnatullin Heads up interesting changes coming to Dagger 2:
https://twitter.com/froger_mcs/status/723453526098194432
https://twitter.com/froger_mcs/status/723454950584516608
https://twitter.com/froger_mcs/status/723454950584516608
https://twitter.com/froger_mcs/status/723456593388556288
https://twitter.com/froger_mcs/status/723457436955320320

**Comment by vanniktech** [comment]
What's the advantage of using `static @Provides` methods rather than `instance @Provides`?!

**Comment by artem-zinnatullin** [comment]
@Plastix yup, saw that, thanks.

@vanniktech to not be able to override this in integration/functional tests? :D

**Comment by vanniktech** [comment]
Hmm okay but in the tweet it says because of #perfmatters. Anyways. Even with Dagger 2.4 we're getting `Generating a MembersInjector for com.artemzin.qualitymatters.QualityMattersApp. Prefer to run the dagger processor over that class instead.`

**Comment by artem-zinnatullin** [comment]
My guess is that they won't fix it. Or it'll take ~1 year.

**Pull request merged**
