### PR TITLE
Switch to Paperwork 1.2.4

### LINKED ISSUE #93: Gradle sync fails all the time
I'm running `sh ci.sh` and the project is built successfully.
However, Android Studio keeps showing me the following error message:

> Gradle project sync failed. Basic functionality (e.g. editing, debugging) will not work properly

Because whenever I try to sync Gradle project I'm getting the following error:

> Error:(4, 0) Cause: hu/supercluster/paperwork/plugin/PaperworkPlugin : Unsupported major.minor version 52.0

I suppose that this may be caused by the incompatibility of bytecode generated by different java compilers. The `JAVA_HOME` on my system points to the Java 7 installation, the `javac -version` output is the 

> javac 1.7.0_80

...and the `java -version` gives me 

> java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

Where does this error may come from?

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
Should resolve #93

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
@agap can you please check this branch?

**Comment by vanniktech** [comment]
:+1:

**Comment by agap** [comment]
@artem-zinnatullin yeah, it works, but I think that it was the one-time glitch. I've switched back to Java 8 which I was using before and tried to build the project from scratch (i.e. removing all the build files) from both branches - master and paperwork-1.2.4. The project builds fine now.

**Comment by artem-zinnatullin** [comment]
Ok, cool!

**Pull request merged**
