### PR TITLE
Update Robolectric to 3.1

### PR DESCRIPTION
**Pull request by Plastix**

### CODE REVIEW

**Comment by vanniktech** [comment]
👍 any of you guys notice any performance change? I've heard 3.1 is slow as hell in comparison to 3.0.

**Comment by artem-zinnatullin** [comment]
We have only one test that runs under robolectric (all other tests are plain jvm tests and others are instrumentation) and I'm going to migrate last robolectric test to instrumentation this week, can't really say.

Lemme ask huge user of robolectric cc @karlicoss: is robolectric 3.1 slower that 3.0?

**Comment by artem-zinnatullin** [comment]
👍

**Comment by artem-zinnatullin** [comment]
Thanks, @Plastix!

**Comment by karlicoss** [comment]
@vanniktech @artem-zinnatullin I've heard of performance downgrades (see https://github.com/robolectric/robolectric/issues/2328), but haven't noticed any significant difference in our project

**Pull request merged**
