### PR TITLE
Update Espresso to 2.2.2

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
No changelog :(

Also, moved it to the bottom to other tests deps.

### CODE REVIEW

**Comment by vanniktech** [comment]
:+1: 

I think you already know by know but retrofit2 was released :tada:

**Comment by artem-zinnatullin** [comment]
Yup, will try to update soon

**Comment by vanniktech** [comment]
Hmm I'm wondering whether Travis was flaky or they actually changed something regarding espresso in 2.2.2 and broke the tests.

**Comment by artem-zinnatullin** [comment]
Build log shows something very bad as far as I remember, not regular Travis
flakiness

On Sun, 20 Mar 2016, 00:09 Niklas Baudy, <notifications@github.com> wrote:

> Hmm I'm wondering whether Travis was flaky or they actually changed
> something regarding espresso in 2.2.2 and broke the tests.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/artem-zinnatullin/qualitymatters/pull/117#issuecomment-198786104>
>
-- 

@artem_zin

**Comment by Yurii-Laguta** [comment]
Change log: https://google.github.io/android-testing-support-library/downloads/release-notes/

**Comment by artem-zinnatullin** [comment]
Thanks!

**Comment by artem-zinnatullin** [comment]
Closing for now, will do in 2.0.

**Pull request closed without merging**
