### PR TITLE
Update gradle wrapper to 2.13

### PR DESCRIPTION
**Pull request by lenguyenthanh**
Change logs: https://docs.gradle.org/2.13/release-notes

### CODE REVIEW

**Comment by vanniktech** [comment]
2.14 should be out soon. RC is already available

**Comment by lenguyenthanh** [comment]
Yeah. I'm waiting for 3.0 where Kotlin is supported too. Very excited about it.

**Comment by artem-zinnatullin** [comment]
@lenguyenthanh you need to update gradle wrapper jar too!

**Comment by lenguyenthanh** [comment]
Updated @artem-zinnatullin

**Comment by vanniktech** [comment]
Hmm I think @artem-zinnatullin meant running `./gradlew wrapper` locally as it'll update the `gradlew`, `jar` files etc.

**Comment by artem-zinnatullin** [comment]
Yup

**Comment by lenguyenthanh** [comment]
Oh ok guys, will update it later today. Thanks!

**Comment by lenguyenthanh** [comment]
Fixed it using gradle wrapper command.

**Comment by vanniktech** [comment]
👍

**Comment by artem-zinnatullin** [comment]
👍 Thanks!

**Pull request merged**
