### PR TITLE
Add Codecov integration with Travis CI

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
Part of #119.

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Yay, it works, now we need to also generate coverage report from functional tests to fulfill ui package coverage

**Comment by artem-zinnatullin** [comment]
So, I've added code coverage for instrumentation tests too (I hate Gradle and Groovy, everything so  implicit, uh)

And updated Jacoco to latest version, release notes: https://github.com/jacoco/jacoco/releases

**Comment by artem-zinnatullin** [comment]
Added badge (heh) to show coverage of the master branch (it will show value after merge of this PR).

So far so good, coverage is 82%, we can improve it in future. After merge I'll setup more rules on the codecov.io to also report status check and fail builds.

@vanniktech, @lenguyenthanh PTAL

**Comment by lenguyenthanh** [comment]
Super cool @artem-zinnatullin . It's more visualization and now we  can look at code coverage directly on the PR. Please add more rules to get better PRs.

**Comment by artem-zinnatullin** [comment]
Status check set fail build if code coverage will be less than 82% from now. 

>Please add more rules to get better PRs.

You mean more checkers like PMD, FindBugs, Lint, etc?

**Comment by lenguyenthanh** [comment]
Like this one
> Status check set fail build if code coverage will be less than 82% from now.

And some rules like: build fail if we decrease code coverage.

**Comment by vanniktech** [comment]
Looking really good and nice :+1:

**Comment by vanniktech** [comment]
@artem-zinnatullin & @lenguyenthanh there's also a really nice [browser extension](https://github.com/codecov/browser-extension#codecov-extension)

**Comment by artem-zinnatullin** [comment]
No Safari support :(

**Comment by vanniktech** [comment]
You're using Safari? :D

**Comment by lenguyenthanh** [comment]
Why not @vanniktech  😄

**Comment by artem-zinnatullin** [comment]
It works faster than Chrome, eats less memory and when I work on MacBook it
lives much longer on battery

**Pull request merged**
