### PR TITLE
Upgrade gradle plugin to latest version

### PR DESCRIPTION
**Pull request by omihaz**
Upgrade gradle plugin to latest stable version 2.1.0

### CODE REVIEW

**Comment by vanniktech** [comment]
@omihaz you also need to adjust the circleci configuration file ;)

**Comment by artem-zinnatullin** [comment]
Please fix the build

**Comment by omihaz** [comment]
Hello. Build may be fixed. Can you restart build? It fails with some strange message.

**Comment by artem-zinnatullin** [comment]
Yeah, sometimes travis is weird about Android SDK components, restarted the build

**Comment by omihaz** [comment]
Sorry, forget about travis ci. PR updated.

**Comment by artem-zinnatullin** [comment]
ping, 2.1.2 plugin is out!

**Comment by omihaz** [comment]
Thanks, PR updated.

**Comment by artem-zinnatullin** [comment]
> Process 'Gradle Test Executor 2' finished with non-zero exit value 137

Damn, looks like Travis run out of memory on build.

**Comment by omihaz** [comment]
Do you try wercker CI service? Maybe it is a good candidate to replace travis?

**Comment by artem-zinnatullin** [comment]
Hm, no, never head of it. Let's see if build on Circle CI pass. We're in process of selecting CI #132 btw

**Comment by omihaz** [comment]
Circle CI: sh ci.sh died unexpectedly

**Comment by artem-zinnatullin** [comment]
CircleCI

>sh ci.sh died unexpectedly

hm, probably OOM too…

**Comment by artem-zinnatullin** [comment]
Damn it. Okay, we can split CI script and build debug, release and test as separate steps to save general memory consumption.

**Comment by artem-zinnatullin** [comment]
I'll do it tonight.

**Comment by omihaz** [comment]
Locally sh ci.sh builds fine.

BUILD SUCCESSFUL

Total time: 2 mins 25.062 secs

**Comment by artem-zinnatullin** [comment]
Yeah, I understand, looks like Android tools team changed something in Gradle Plugin or build tools so building consumes more memory

**Comment by artem-zinnatullin** [comment]
Update: I wrote the script and now the problem is that for some reason finbugs finding issues in code that it didn't scan before I guess, so I need to solve and I'll open a PR

**Comment by artem-zinnatullin** [comment]
Sorry for delay, #184 won battle with CI, thanks for contribution @omihaz!

**Pull request closed without merging**
