### PR TITLE
Update Jackson to 2.8.1

### PR DESCRIPTION
**Pull request by vanniktech**

### CODE REVIEW

**Comment by serj-lotutovici** [comment]
@artem-zinnatullin can I ask why you choose Jackson over moshi?

**Comment by Plastix** [comment]
Good question! Personally, I have been using GSON.

**Comment by vanniktech** [comment]
I guess flexibility. I'm also stuck with it and can't move that easily to Moshi.

**Comment by serj-lotutovici** [comment]
Moshi is an evolution of Gson... basically developed by the same people. I've beed using it for almost a year now, and it's really awesome.

@vanniktech the migration should be fairly simple if you have one single place, especially if you use retrofit...

**Comment by vanniktech** [comment]
Yeah usually it is. Though we'd need to write custom adapters for every model class since some fields should be sent when `null`, other should not. Some only when they're not empty, some are read only etc. the list goes on. We're also in the process of migrating to a new database where all of the new models will be AutoValue'd hence we'll go for this one first and then afterwards let an annotation processor generate the converters in order to be used with Moshi.

**Comment by artem-zinnatullin** [comment]
I personally now prefer Moshi too, Jackson just has builders support out of the box -> AutoValue support.

👍

**Pull request merged**
