### PR TITLE
Removed deprecated RobolectricGradleTestRunner.

### PR DESCRIPTION
**Pull request by zsavely**
More info [here](https://github.com/robolectric/robolectric/pull/2517).

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Nice! I'm actually haven't watched Robolectric for like half a year and glad to see such changes

**Comment by vanniktech** [comment]
Uh nice since when is it deprecated? I'm also happy to see it.

**Comment by vanniktech** [comment]
Uh that change looks fantastic. Thanks for that I'll also change it.

**Comment by artem-zinnatullin** [comment]
God, the more I work on OSS on GitHub the more I don't like free (yes, it's free, I understand) cloud CI… restarted CircleCI build (died unexpectedly)

**Comment by Plastix** [comment]
Thanks for the heads up! I'll update my person projects that use Roboelectric as well.

**Comment by artem-zinnatullin** [comment]
Thanks, @zsavely!

**Comment by zsavely** [comment]
No problem! 👍

**Pull request merged**
