### PR TITLE
Remove unuse @Inject on ItemPresenter class

### PR DESCRIPTION
**Pull request by lenguyenthanh**

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
:+1:

**Comment by vanniktech** [comment]
:+1: codecov again complaining

**Comment by artem-zinnatullin** [comment]
Thanks! Yeah, codecov doesn't like deleting code :)

**Comment by lenguyenthanh** [comment]
It looks strange ;) I think deleting code can increase code coverage but actually it decreases :D

**Pull request merged**
