### PR TITLE
Update RxJava to 1.1.5

### PR DESCRIPTION
**Pull request by egor-n**
https://github.com/ReactiveX/RxJava/blob/1.x/CHANGES.md#version-115---may-5-2016-maven

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
:+1:

**Comment by vanniktech** [comment]
👍

**Comment by lenguyenthanh** [comment]
👍 it comes so fast lol

**Comment by vanniktech** [comment]
There was a bug in `1.1.4` and `1.1.5` is more like a 'hotfix' for that.

**Pull request merged**
