### PR TITLE
Add Circle CI config file

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
Part of #132.

### CODE REVIEW

**Comment by vanniktech** [comment]
Don't you think we'll have problems if we run `codecov` on both ci's?

**Comment by artem-zinnatullin** [comment]
@vanniktech nope, it should override status on GitHub, nothing too bad :)

**Comment by artem-zinnatullin** [comment]
finally circle config is ok, build passes (and travis failed btw)

**Comment by artem-zinnatullin** [comment]
Squashed

**Comment by artem-zinnatullin** [comment]
@vanniktech ptal when you'll have some time :)

**Comment by vanniktech** [comment]
Uh nice :+1:

**Pull request merged**
