### PR TITLE
Add a comment about versionCode + CI

### PR DESCRIPTION
**Pull request by artem-zinnatullin**

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
@vanniktech any input?

**Comment by vanniktech** [comment]
@zsoltk did a really awesome gradle plugin for that. We should definitely use that [one](https://github.com/zsoltk/paperwork)

We might even be able to extend some functionality, if we can find anything and improve paperwork.

Also since it's external, everyone can use it and not just qualitymatters

**Comment by artem-zinnatullin** [comment]
Wait, but how it related to versionCode? 

I see the value of the plugin for other build info so, let's try it! (in a separate PR)
Though, personally, I'd prefer more generic version of the plugin that won't know about Git and Build time format, otherwise looks good, love `extra` ability.

**Comment by zsoltk** [comment]
@artem-zinnatullin I could make those configurable as well, with their current value being the overridable default. How about that?

**Comment by artem-zinnatullin** [comment]
Well, for our case it's okay :smile_cat: But just think about those who use VCS other than Git and those who don't need build date

**Comment by vanniktech** [comment]
@artem-zinnatullin I totally mixed the PR up

**Comment by zsoltk** [comment]
@artem-zinnatullin You mentioned in your comment the format of the git and build time info, so I addressed that in my reply. But yeah, you are right, this could be even more generic :)

Like I said, I'm open to discussion as in which direction the plugin should evolve, and how to make its features more pluggable. I invite you and @vanniktech both to collaborate and submit your ideas and make it better!

**Comment by vanniktech** [comment]
@zsoltk I'll most definitely collaborate to it once I'm back home

**Pull request merged**
