### PR TITLE
Add Jacoco exclude for Kotlin

### PR DESCRIPTION
**Pull request by artem-zinnatullin**

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Disclaimer: with this exclude Jacoco able to generate report for Kotlin classes, but it also detects some problems like:

```
Classes in bundle 'projectname' do no match with execution data. 
For report generation the same class files must be used as at runtime.

[ant:jacocoReport] Execution data for class MyClass does not match.
[ant:jacocoReport] Execution data for class AnotherClass does not match.

```

**Comment by lenguyenthanh** [comment]
When I use Jacoco for Kotlin project, I don't like the way it includes all generated code to its report. Do you know how to make Jacoco exclude those generated code, @artem-zinnatullin ?

**Comment by artem-zinnatullin** [comment]
Can you provide an example? I'll check in project I work on too

**Comment by lenguyenthanh** [comment]
data-class
It looks like the image above. Jacoco counts equals() and hash(), etc to the report. In the other hand, I think it has some problems with inline function. In my current project, it couldn't create report any more.

**Comment by artem-zinnatullin** [comment]
@lenguyenthanh I'm kind of stopped playing with Jacoco + Kotlin for now, I hope to integrate codecov into work project soon so I'll revisit this issue

**Pull request merged**
