### PR TITLE
Update to AS 2.2.1 & Gradle 3.1. Got rid of apt

### PR DESCRIPTION
**Pull request by vanniktech**
- update to Gradle Android Tools 2.2.1
- update to gradle 3.1 (better performance yeah)
- get rid of apt (2.2.0 can do this now)

### CODE REVIEW

**Comment by vanniktech** [comment]
Also needed to update the dexcount plugin since the version used is not compatible with Gradle 3.x the newer ones are though.

**Comment by vanniktech** [comment]
I think travis timed out. Can you restart it?

**Comment by vanniktech** [comment]
Oh nice you already did thanks :)

**Comment by artem-zinnatullin** [comment]
Thanks!

**Comment by thevery** [comment]
btw you don't need custom lombok with gradle 2.2: https://twitter.com/jakewharton/status/777954097148358656

**Comment by Plastix** [comment]
@thevery My lint still fails without custom lombok using Android Gradle Plugin 2.2.0.

**Comment by vanniktech** [comment]
Same here

**Pull request merged**
