### PR TITLE
Disable AndroidDevMetrics during unit tests

### PR DESCRIPTION
**Pull request by Plastix**
This fixes the issue I've been having with Android Studio not running
Roboelectric tests. All the tests pass locally on my system. Thoughts @artem-zinnatullin? 

@vanniktech Please tell me if this fixes your issue as well!

### CODE REVIEW

**Comment by vanniktech** [comment]
Wohooo that's brilliant \o/ :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by Plastix** [comment]
Awesome! Will do.

**Comment by artem-zinnatullin** [comment]
Oh lol… cc @frogermcs see #145.

**Comment by lenguyenthanh** [comment]
Great, though I never experiment this problem.

**Comment by Plastix** [comment]
Judging from the discussion here https://github.com/frogermcs/AndroidDevMetrics/issues/20 I think this PR is the correct solution.

**Comment by artem-zinnatullin** [comment]
:+1:

**Comment by artem-zinnatullin** [comment]
@Plastix thanks for investigation!

**Pull request merged**
