### PR TITLE
Fix typo.

### PR DESCRIPTION
**Pull request by skoric**
Sorry, hurts my soul :smile:.
> Obsessive–compulsive disorder (OCD) is a mental disorder where people feel the need to check things repeatedly, to perform certain routines repeatedly, or have certain thoughts repeatedly.

### CODE REVIEW

**Comment by vanniktech** [comment]
@skoric it seems like you missed something there while renaming

**Comment by skoric** [comment]
@vanniktech yup, in `/release` directory, AS didn't pick up on it when renaming. Thanks :+1:

**Comment by vanniktech** [comment]
Looks good to me :+1:

**Comment by artem-zinnatullin** [comment]
Haha :)

**Comment by artem-zinnatullin** [comment]
@skoric thanks for PR!

@vanniktech thanks for review!

**Pull request merged**
