### PR TITLE
Add build info: git sha, date, version code and version name to the Developer Settings

### PR DESCRIPTION
**Pull request by artem-zinnatullin**

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Yep, there is a comment in `build.gradle` that says that. But, usually, every git commit breaks incremental compilation anyway :)

**Comment by zsoltk** [comment]
I'd argue that having this extra info is not worth the increased build times. Since this is *the* #qualitymatters app, why not go the extra mile and approach the problem along the lines Jake Wharton explained it in [this comment](https://www.reddit.com/r/androiddev/comments/3az8qd/add_a_git_sha_to_your_crash_reporting_tools/cshk90h)

Proposal:
1. have a mechanism to generate git sha and build time to an asset file (if nothing else, a shell script that gets executed from build.gradle - is there a better way to do this?)
2. have a class that provides getters to said information and lazily reads the asset file upon first request

**Comment by vanniktech** [comment]
I agree with @zsoltk 

Maybe we could let a gradle plugin or task hook up into the `assemble` tasks in Gradle and generate the file with the information (build date / time + git commit and maybe the last tag) and move it into assets or the res/raw directory.

**Comment by artem-zinnatullin** [comment]
Asset file is nice approach, and as first solution we could do it via simple Gradle task without wrtiting external plugin, here is the issue to track this #72

Thanks for the input @zsoltk & @vanniktech!

**Comment by zsoltk** [comment]
Since I already wanted to do this for a long time now, I threw together a gradle plugin + runtime lib overnight to do this task. Please welcome: https://github.com/zsoltk/paperwork

**Comment by vanniktech** [comment]
Oh that looks really awesome!

**Comment by artem-zinnatullin** [comment]
We'll try it! See #75

**Comment by zsoltk** [comment]
Great! Should you have any questions or suggestions, tell me.

**Pull request merged**
