### PR TITLE
Update gradle scan 1.3

### PR DESCRIPTION
**Pull request by caipivara**

### CODE REVIEW

**Comment by caipivara** [comment]
Looks like it fails on Circle CI for some reason waiting for the emulator... but Im not sure what to do there, can you rerun the tests to see if they pass?

**Comment by artem-zinnatullin** [comment]
Yeah, Android Emulator is flaky af `no devices/emulators found`, restarted the build

**Comment by artem-zinnatullin** [comment]
Uh, I've disabled Circle CI for now, too flaky

**Comment by artem-zinnatullin** [comment]
Thanks for PR!

**Pull request merged**
